# Generated by Django 2.2.2 on 2019-08-07 02:04

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('severity', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('cwe', models.IntegerField(blank=True)),
                ('rule', django_mysql.models.SetTextField(models.CharField(max_length=32), size=None)),
                ('tool', models.CharField(max_length=32)),
                ('location', models.TextField()),
                ('element', models.CharField(max_length=32)),
                ('path', models.TextField()),
                ('line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XMLIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('sourcefile', models.TextField()),
                ('startLine', models.IntegerField()),
                ('endLine', models.IntegerField()),
                ('group', models.CharField(max_length=20)),
                ('code', models.TextField()),
                ('severity', models.CharField(max_length=10)),
                ('rule', django_mysql.models.SetTextField(models.CharField(max_length=32), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.AddField(
            model_name='xmlissue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cas.Report'),
        ),
        migrations.AddField(
            model_name='csvissue',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cas.Report'),
        ),
    ]
